### ISSUE TITLE
生成过程中报错, 似乎是文件夹创建的问题

### ISSUE THREAD

**Issue by Yi-Frank** [aliyun/darabonba-csharp-generator#29]
在使用`dara codegen csharp ./tmp`过程中报错
```
Error: ENOENT: no such file or directory, mkdir './tmp/core'
    at Object.mkdirSync (fs.js:731:3)
    at new Visitor (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/node_modules/@darabonba/csharp-generator/lib/generator.js:56:10)
    at generateCode (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/commands/codegen.js:30:21)
    at CodegenCommand.exec (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/commands/codegen.js:118:5)
    at CommandsApplication.exec (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/lib/app.js:137:13)
    at CommandsApplication.run (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/lib/app.js:29:12)
    at Object.<anonymous> (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/bin/dara.js:46:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

若使用`dara codegen csharp ./`则报错
```
Error: EEXIST: file already exists, mkdir 'core'
    at Object.mkdirSync (fs.js:731:3)
    at Visitor.save (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/node_modules/@darabonba/csharp-generator/lib/generator.js:71:8)
    at Visitor.visitModule (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/node_modules/@darabonba/csharp-generator/lib/generator.js:213:10)
    at Visitor.visit (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/node_modules/@darabonba/csharp-generator/lib/generator.js:66:10)
    at generateCode (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/commands/codegen.js:35:13)
    at CodegenCommand.exec (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/commands/codegen.js:118:5)
    at CommandsApplication.exec (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/lib/app.js:137:13)
    at CommandsApplication.run (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/lib/app.js:29:12)
    at Object.<anonymous> (/root/.nvm/v10.10.0/lib/node_modules/@darabonba/cli/bin/dara.js:46:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

查看了您的源码后看上去好像是文件夹新建层级的缘故...没有办法在不建立上层文件夹的情况下直接建立下层文件夹...系统环境是centos7.4...
同样出现这样问题的还有java....但php, python, ts等均为出现问题...
```
this.config = Object.assign({
      outputDir: '',
      indent: '    ',
      clientPath: `${option.className || 'Client'}.cs`
    }, option);
    assert.ok(this.config.outputDir, '`option.outputDir` should not empty');
    assert.ok(this.config.namespace, `Darafile -> csharp -> namespace should not empty, please add csharp option into Darafile.
      example:
        "csharp": {
          "namespace": "NameSpace",
          "className": "Client"
        }`);
    this.namespace = option.namespace;
    this.className = option.className || 'Client';
    this.output = '';
    this.outputDir = this.config.outputDir + '/core';
    this.csprojOutputDir = option.outputDir + '/core';
    this.release = option.releases && option.releases.csharp || this.namespace + ':0.0.1';
    this.config.packageInfo = this.config.packageInfo || {};

    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, {
        recursive: true
      });
    }
```

**Comment by Yi-Frank** [comment]
找到原因了, 是node版本的问题, 升级到15.2之后该问题消失....但建议针对不同node版本做出提示或警告~

**Comment by JacksonTian** [comment]
@Yi-Frank 感谢您的反馈。这个问题我们就暂时搁置吧，应该 node 12 后都是正常的。
